### ISSUE TITLE
How to build the 2D view expected in the app?

### ISSUE THREAD

**Issue by Abdelkrim** [MicrosoftDX/AzureLens#1]
to whom it may concern,
I wonder what you had in mind when you added the "2D" feature in the Azure Lens application?

Could you tell me how you planned to implement it? 

I am currently building a 2D app using BabylonJS

btw, your 3D visual is neat, the code too :-)

Thank you for your feedback

**Comment by matvelloso** [comment]
Hey,

Well I had two ideas on that: One would be to just keep using Babylon, but have the camera just doing geometric projection straight from the top. The second one would be using a totally different framework for rendering it in purely 2D what would be more lightweight. The reason why we didn't invest much on that already is because we have some friends doing something very similar in that 2D space: http://armviz.io/

**Comment by Abdelkrim** [comment]
@matvelloso, thank you for the feedback, I have looked at armviz and indeed it ressembles to our goal : https://bitly.com/SIMOGGAVideosOnYoutube (this isn't a spam, nor a scam just our videos on youtube)
